### ISSUE TITLE
Problems when ignoring the Ø character

### ISSUE THREAD

**Issue by theplatapi** [andyhu/transliteration#26]
**Problem**
Spaces before the Ø character are removed

**Expected Output**
Twenty Øne Piløts

**Actual Output**
TwentyØne Pilots

**Version**
1.3.0, in the transliteration demo

**Comment by andyhu** [comment]
Thanks for the spot, I'll take a look and fix it asap.

**Comment by andyhu** [comment]
Hi @theplatapi,
I have tested the module and it seems not having this issue. Please check the screenshot:
![Screenshot](http://i.imgur.com/P9zTpnwl.png)
It's using 1.3.0 browser version
http://rawgit.com/andyhu/transliteration/master/demo/example.html
I'll close this issue for now. If you still think it's an issue, please let me know how to reproduce it.
Many thanks!

**Comment by theplatapi** [comment]
I should have repeated it in the body of the issue, but the problem happens when I want to ignore the Ø character. 

![screen shot 2017-02-02 at 12 08 39 am](https://cloud.githubusercontent.com/assets/5661209/22541546/ddb664a0-e8db-11e6-886e-b8adf9a67a6c.png)

I want the Ø character to be in the final output, but the space before it is removed.

**Comment by andyhu** [comment]
It's now fixed in v1.4.1
