### ISSUE TITLE
Issue running with React Native

### ISSUE THREAD

**Issue by theplatapi** [andyhu/transliteration#27]
Using React Native, the module crashes when called, only when hot reloading is disabled. When hot reloading is enabled then it works.

```
error TypeError: babelHelpers.typeof is not a function
    at mergeOptions
    at transliterate
```

The raw Babel transpiled code looks like this:
```
if(key==='replace'&&babelHelpers.typeof(result[key])==='object'&&!(result[key]instanceof Array)){
```

I'm including transliterate as follows
```
import { transliterate } from 'transliteration/src/main/browser';
```

I notice that `transliteration/lib/node/utils.js` uses a custom typeOf to avoid the problem, but for some reason it's trying to use `transliteration/src/main/utils.js` that has babel replace the typeof operator with it's own.

**Comment by andyhu** [comment]
Hi @theplatapi,
Please test again with v1.5.1. Let me know if it works, thanks!

**Comment by theplatapi** [comment]
@andyhu Yup, this fixes the problem. Thank you for your help!
