### ISSUE TITLE
Version 1.5.3 'leaks' ES6 code (let, const) into minified js bundle when built

### ISSUE THREAD

**Issue by spencern** [andyhu/transliteration#38]
I've got an issue that seems related to #28 

I've got a meteor app (meteor controls the build) that imports `transliteration` - there's a description of the problem and a reproduction based on our app here: https://github.com/reactioncommerce/reaction/pull/2091

For versions up to 1.5.2 transliteration bundles a correctly babelified and minified js file. When we got bumped up to 1.5.3, we started seeing `let` and `const` in our minified production bundle. I think this is due to the change for 1.5.3 that removed the `"browser": "lib/browser/transliteration.js",` line, and the conversation in #28 seems to point that direction as well.

This issue only causes problems for us when an older browser such as PhantomJS is used to crawl the site. Unfortunately, the prerendering techniques we use to create cached, google/bing/yahoo crawl friendly pages use PhantomJS, and the `let` and `const` in the js bundle causes them to crash before rendering.

**Comment by andyhu** [comment]
Hi,
Thanks for the spot, I'll investigate this issue today and get back to you a bit later. Adding `"browser": "lib/browser/transliteration.js"` actually cause other problems, someone had reported an issue running in reactnative.

**Comment by lcampanis** [comment]
Hi @spencern! Have a look at https://github.com/andyhu/transliteration/pull/39

**Comment by spencern** [comment]
@andyhu 
I've not tried manually importing it yet. I can give that a shot. Thanks for the prompt response

**Comment by spencern** [comment]
@lcampanis I'll take a look!

**Comment by andyhu** [comment]
Hi, sorry for the lack of response. I've been very busy. I have done some work to try to fix this issue. Could you test again with version 1.6.0? If there's still any issues, please let me know. Thanks!

**Comment by spencern** [comment]
I'll do that @andyhu. Thanks

**Comment by kachkaev** [comment]
See https://github.com/andyhu/transliteration/pull/44 - might help

**Comment by spencern** [comment]
It appears that this is working for us now with the latest version of transliteration (1.6.2) by importing the minified version.
e.g.
```
import "transliteration/lib/browser/transliteration.js";
```

Closing this issue for now

**Comment by kachkaev** [comment]
It is discouraged to use pre-built packages in webpack, because this way you import _all the code_ without giving webpack an opportunity to only bundle the stuff that's actually being used.

**Comment by spencern** [comment]
Hi @kachkaev - I agree that it's not ideal, but it was suggested to us by @andyhu and is currently working. We're using Meteor and not webpack currently and working on moving transliteration to a dynamic import as well so it's only loaded for users who need it.

I saw your PR, if that gets pulled in, we'll try that as well and see if we can stop importing the pre-built package.
