### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by AhHa45** [andyhu/transliteration#45]
Can you make this compatible with Angular and/or show us how to use it in Angular with TypeScript?

**Comment by andyhu** [comment]
Hi, thanks for using this module. However I'm not familiar with both Angular or TypeScript, would you elaborate how it's not compatible with them?

**Comment by ConquerorsHaki** [comment]
thx for the update.

**Comment by andyhu** [comment]
Update:
Since v1.6.6, Typescript definition is added.
v2 will be rewritten entirely in Typescript. I'll just close this issue. If there is more questions please comment.
