### ISSUE TITLE
TypeScript type definition support

### ISSUE THREAD

**Issue by linkFly6** [andyhu/transliteration#63]
I like typescript and transliteration, but transliteration doesn't support typescript.

If you can't support typescript [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), I'd like to contribute to the code.

**Comment by andyhu** [comment]
Hi, sorry for the reply. I'm not quite familiar with TypeScript, so I'd appreciate if you could submit a PR. Thanks!

**Comment by linkFly6** [comment]
pull request.

Support for typescript in node. 

But I didn't use bower, so I don't know how to support bower.

另外我换中文了....

目前浏览器端和 bower 引入没有支持，而 bower 没用过所以不知道如何支持，也不知道能不能支持...

现在 node 直接引入就可以支持了。

![image](https://user-images.githubusercontent.com/6982402/43249093-5c2ba692-90ec-11e8-995d-3dd86698d178.png)

正常使用会有对应的 API 提示，ts 中使用会开启类型检查。

**Comment by andyhu** [comment]
Thanks for contributing, I've already merged your PR. 谢谢贡献代码，我已合并你的PR
因为没怎么用过typescript所以我也不太明白bower要怎么支持。不过有打算要取消bower支持了，没什么用，webpack / cdn 两种就够了

**Comment by linkFly6** [comment]
建议在声明文件的头部声明一下版本和 ts 支持的版本，以便让 ts 使用者了解对应的版本和 ts 兼容性详细信息：

`types/index.d.ts`:

```ts
// Type definitions for transliteration 1.6.6
// Project: https://github.com/andyhu/transliteration
// Definitions by: linkFly <linkFly6@live.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.9.2
```

如果后续有 ts 兼容问题欢迎再联系我。

**Comment by andyhu** [comment]
Just for reference, I'm going to rewrite 2.0 of this module in Typescript

**Comment by dzcpy** [comment]
@linkFly6 Hi, 2.0 版本已经实现完全采用了Typescript改写，但是我对Typescript并不精通，所以如果有一些地方写的不符合常规或者有什么问题也欢迎提出
